/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DoctorIndexRouteImport } from './routes/doctor.index'
import { Route as DoctorProfileRouteImport } from './routes/doctor.profile'
import { Route as DoctorPatientsRouteImport } from './routes/doctor.patients'
import { Route as DoctorMedicalRecordsRouteImport } from './routes/doctor.medical-records'
import { Route as DoctorLabRequestsRouteImport } from './routes/doctor.lab-requests'
import { Route as DoctorAppointmentsRouteImport } from './routes/doctor.appointments'
import { Route as DoctorPatientsIdRouteImport } from './routes/doctor.patients.$id'
import { Route as DoctorConsultationIdRouteImport } from './routes/doctor.consultation.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorProfileRoute = DoctorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorPatientsRoute = DoctorPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorMedicalRecordsRoute = DoctorMedicalRecordsRouteImport.update({
  id: '/medical-records',
  path: '/medical-records',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorLabRequestsRoute = DoctorLabRequestsRouteImport.update({
  id: '/lab-requests',
  path: '/lab-requests',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorAppointmentsRoute = DoctorAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorPatientsIdRoute = DoctorPatientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DoctorPatientsRoute,
} as any)
const DoctorConsultationIdRoute = DoctorConsultationIdRouteImport.update({
  id: '/consultation/$id',
  path: '/consultation/$id',
  getParentRoute: () => DoctorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/doctor': typeof DoctorRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/lab-requests': typeof DoctorLabRequestsRoute
  '/doctor/medical-records': typeof DoctorMedicalRecordsRoute
  '/doctor/patients': typeof DoctorPatientsRouteWithChildren
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor/': typeof DoctorIndexRoute
  '/doctor/consultation/$id': typeof DoctorConsultationIdRoute
  '/doctor/patients/$id': typeof DoctorPatientsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/lab-requests': typeof DoctorLabRequestsRoute
  '/doctor/medical-records': typeof DoctorMedicalRecordsRoute
  '/doctor/patients': typeof DoctorPatientsRouteWithChildren
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor': typeof DoctorIndexRoute
  '/doctor/consultation/$id': typeof DoctorConsultationIdRoute
  '/doctor/patients/$id': typeof DoctorPatientsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/doctor': typeof DoctorRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/lab-requests': typeof DoctorLabRequestsRoute
  '/doctor/medical-records': typeof DoctorMedicalRecordsRoute
  '/doctor/patients': typeof DoctorPatientsRouteWithChildren
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor/': typeof DoctorIndexRoute
  '/doctor/consultation/$id': typeof DoctorConsultationIdRoute
  '/doctor/patients/$id': typeof DoctorPatientsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/doctor'
    | '/login'
    | '/register'
    | '/doctor/appointments'
    | '/doctor/lab-requests'
    | '/doctor/medical-records'
    | '/doctor/patients'
    | '/doctor/profile'
    | '/doctor/'
    | '/doctor/consultation/$id'
    | '/doctor/patients/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/doctor/appointments'
    | '/doctor/lab-requests'
    | '/doctor/medical-records'
    | '/doctor/patients'
    | '/doctor/profile'
    | '/doctor'
    | '/doctor/consultation/$id'
    | '/doctor/patients/$id'
  id:
    | '__root__'
    | '/'
    | '/doctor'
    | '/login'
    | '/register'
    | '/doctor/appointments'
    | '/doctor/lab-requests'
    | '/doctor/medical-records'
    | '/doctor/patients'
    | '/doctor/profile'
    | '/doctor/'
    | '/doctor/consultation/$id'
    | '/doctor/patients/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DoctorRoute: typeof DoctorRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/profile': {
      id: '/doctor/profile'
      path: '/profile'
      fullPath: '/doctor/profile'
      preLoaderRoute: typeof DoctorProfileRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/patients': {
      id: '/doctor/patients'
      path: '/patients'
      fullPath: '/doctor/patients'
      preLoaderRoute: typeof DoctorPatientsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/medical-records': {
      id: '/doctor/medical-records'
      path: '/medical-records'
      fullPath: '/doctor/medical-records'
      preLoaderRoute: typeof DoctorMedicalRecordsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/lab-requests': {
      id: '/doctor/lab-requests'
      path: '/lab-requests'
      fullPath: '/doctor/lab-requests'
      preLoaderRoute: typeof DoctorLabRequestsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/appointments': {
      id: '/doctor/appointments'
      path: '/appointments'
      fullPath: '/doctor/appointments'
      preLoaderRoute: typeof DoctorAppointmentsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/patients/$id': {
      id: '/doctor/patients/$id'
      path: '/$id'
      fullPath: '/doctor/patients/$id'
      preLoaderRoute: typeof DoctorPatientsIdRouteImport
      parentRoute: typeof DoctorPatientsRoute
    }
    '/doctor/consultation/$id': {
      id: '/doctor/consultation/$id'
      path: '/consultation/$id'
      fullPath: '/doctor/consultation/$id'
      preLoaderRoute: typeof DoctorConsultationIdRouteImport
      parentRoute: typeof DoctorRoute
    }
  }
}

interface DoctorPatientsRouteChildren {
  DoctorPatientsIdRoute: typeof DoctorPatientsIdRoute
}

const DoctorPatientsRouteChildren: DoctorPatientsRouteChildren = {
  DoctorPatientsIdRoute: DoctorPatientsIdRoute,
}

const DoctorPatientsRouteWithChildren = DoctorPatientsRoute._addFileChildren(
  DoctorPatientsRouteChildren,
)

interface DoctorRouteChildren {
  DoctorAppointmentsRoute: typeof DoctorAppointmentsRoute
  DoctorLabRequestsRoute: typeof DoctorLabRequestsRoute
  DoctorMedicalRecordsRoute: typeof DoctorMedicalRecordsRoute
  DoctorPatientsRoute: typeof DoctorPatientsRouteWithChildren
  DoctorProfileRoute: typeof DoctorProfileRoute
  DoctorIndexRoute: typeof DoctorIndexRoute
  DoctorConsultationIdRoute: typeof DoctorConsultationIdRoute
}

const DoctorRouteChildren: DoctorRouteChildren = {
  DoctorAppointmentsRoute: DoctorAppointmentsRoute,
  DoctorLabRequestsRoute: DoctorLabRequestsRoute,
  DoctorMedicalRecordsRoute: DoctorMedicalRecordsRoute,
  DoctorPatientsRoute: DoctorPatientsRouteWithChildren,
  DoctorProfileRoute: DoctorProfileRoute,
  DoctorIndexRoute: DoctorIndexRoute,
  DoctorConsultationIdRoute: DoctorConsultationIdRoute,
}

const DoctorRouteWithChildren =
  DoctorRoute._addFileChildren(DoctorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DoctorRoute: DoctorRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
